let _ = "Mint DAU token 1000000";
let account1 = principal "u4f2v-igzyj-kgr2d-ipjf5-dnkz6-sl6mm-gxues-usbeb-2bthn-pfjdq-kae";
let account2 = principal "g27n3-ynszd-oh3rr-p3xnx-vuhl4-nufyt-xlbbw-x4fsg-5pbiv-jwbkk-7qe";
let account3 = principal "psgm7-igfya-7g2cx-t5jgr-uxozt-fm7n6-xhepm-tvmw7-y4hpe-iq5o4-7qe";
let assetCanister = principal "sbzkb-zqaaa-aaaaa-aaaiq-cai";
let assetSc = record { canister_id = principal "sbzkb-zqaaa-aaaaa-aaaiq-cai" };
let assetStore = record { canister_id = principal "si2b5-pyaaa-aaaaa-aaaja-cai" };
let assetStoreCanister = principal "si2b5-pyaaa-aaaaa-aaaja-cai";
let dip20 = record { canister_id = principal "q4eej-kyaaa-aaaaa-aaaha-cai" };
let dip20Canister = principal "q4eej-kyaaa-aaaaa-aaaha-cai";
let dip721Canister = principal "q3fc5-haaaa-aaaaa-aaahq-cai";
let ic = principal "aaaaa-aa";
let marketplace = record { canister_id = principal "sp3hj-caaaa-aaaaa-aaajq-cai" };
let marketplaceCanister = principal "sp3hj-caaaa-aaaaa-aaajq-cai";
let nftSc = record { canister_id = principal "q3fc5-haaaa-aaaaa-aaahq-cai" };
let resp = variant { Ok = 5 : nat };
let stakingCanister = principal "sgymv-uiaaa-aaaaa-aaaia-cai";
let stakingSc = record { canister_id = principal "sgymv-uiaaa-aaaaa-aaaia-cai" };
